---
title       : Shiny app presentation
subtitle    : Comparing unemployment rates
author      : José Luis Cañadas Reche
job         : IESA-CSIC
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Why

Unemployment  rate is the principal economic problem in Spain. Spanish regions have different kind of unemployment rate. Age and education are important variables in order to get a job.  It has sense  research their  unemployment rate evolution across the regions

[EPA microdata](http://www.ine.es/en/inebaseDYN/epa30308/epa_microdatos_en.htm) is the official survey to research labour market. It's a panel where the people have interviewed each 3 months. In each wave, around 170,000 persons answer the survey.

Previously we have calculated unemployment rate by region, age groups and education level for each period since 2008. You can see how to do for one particular wave in this [rpubs document](http://rpubs.com/joscani/unemplrate)

With this app we can explore how to change unemployment rate across the time

---

## Unemployment rate
<style>
strong {
  font-weight: bold;
}
em {
  font-style: italic;
}
</style>
Some definitions:

* Population of 16 years old or older is subdivided in active + inactive population
* Active population :  employed + unemployed 
* Inactive population: Students, retired, unable to work and other situations

* __Unemployment rate__ : It is the ratio between the number of unemployed and active population.

We calculate unemployment rate for each combination of region, age group, education level and period since 2008 and put together in a data.frame

---


## Data

Data are in master branch in github repository
https://github.com/joscani/project_shiny/tree/master

```{r}

load("../data.rda")
dim(data)
data[1:3,]
```

---

## The App
<style>
strong {
  font-weight: bold;
}
em {
  font-style: italic;
}
</style>
App is hosting in https://canadasreche.shinyapps.io/project_shiny/

* ggplot line figure : unemployment rate evolution since 2008. 
    * 2 facets: education level and age groups
    * You can choose 2 differents regions and compare evolution
    
* Table with unemployment rate for a choosen region, education level and period interval.

Example: Unemployment rate for age group 35-54 years old and *primary* education level has changed from 12.93% in 2008 to 42.38% for 2014 in Spain. Awful!! 









